[tox]
envlist = lint, format

[testenv:lint]
description = Run flake8 for linting
deps = flake8
commands = flake8 automation

[testenv:format]
description = Run formatters for Python, JavaScript, HTML, and Markdown
deps = 
    prettier
allowlist_externals =
    prettier
commands =
    prettier --write .
